server:
  port: 8089
  servlet:
    context-path: /

spring:
  application:
    name: open-demo-java
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    org.springframework:
      data: DEBUG
      sercurity: DEBUG
